export const AUTH_ERRORS = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_INACTIVE: 'USER_INACTIVE',
  ORGANIZATION_INACTIVE: 'ORGANIZATION_INACTIVE',
  ORGANIZATION_MISMATCH: 'ORGANIZATION_MISMATCH',
  UNEXPECTED_ERROR: 'UNEXPECTED_ERROR',
} as const;

export const AUTH_MESSAGES = {
  LOGIN_SUCCESS: 'User logged in successfully',
} as const;
