'use client';

import React, { useState, useEffect } from 'react';
import { RoleRoute } from '@/components/auth';
import { apiClient } from '@/lib/api';
import {
  Page,
  PageHeader,
  Card,
  CardHeader,
  CardTitle,
  CardBody,
  Button,
  Badge,
  Field,
  TextInput,
} from '@shared/ui/components';
import {
  ShieldCheck,
  Sliders,
  CheckCircle2,
  RefreshCw,
  Server,
  Terminal,
  Database,
  Save,
} from 'lucide-react';

interface HealthResponse {
  status: string;
  timestamp?: string;
  uptime?: number;
}

interface AuditRecord {
  id: string;
  correlationId: string;
  method: 'GET' | 'POST' | 'PATCH' | 'DELETE';
  url: string;
  statusCode: number;
  role: string;
  ip: string;
  durationMs: number;
  timestamp: string;
}

export default function AdminSettingsPage() {
  const [health, setHealth] = useState<HealthResponse | null>(null);
  const [isHealthLoading, setIsHealthLoading] = useState(true);

  // Settings form state
  const [settings, setSettings] = useState({
    slotWindowDays: 14,
    cancellationNoticeHours: 2,
    enableEmailAlerts: true,
    enableAuditInterceptor: true,
    maxSlotsPerBulk: 50,
  });
  const [saveSuccess, setSaveSuccess] = useState(false);

  // Simulated live security audit logs generated by AuditLoggerInterceptor
  const [auditLogs] = useState<AuditRecord[]>([
    {
      id: 'aud-1',
      correlationId: 'c7b2a190-4e3f-412d-9011-8899aabbcc11',
      method: 'POST',
      url: '/api/v1/slots/bulk',
      statusCode: 201,
      role: 'DOCTOR',
      ip: '127.0.0.1',
      durationMs: 42,
      timestamp: new Date(Date.now() - 1000 * 60 * 2).toLocaleTimeString(),
    },
    {
      id: 'aud-2',
      correlationId: 'f812d34a-99bb-4112-a234-[audit-trace-2]',
      method: 'GET',
      url: '/api/v1/appointments',
      statusCode: 200,
      role: 'ADMIN',
      ip: '127.0.0.1',
      durationMs: 18,
      timestamp: new Date(Date.now() - 1000 * 60 * 5).toLocaleTimeString(),
    },
    {
      id: 'aud-3',
      correlationId: 'e4598122-1002-4889-b123-[audit-trace-3]',
      method: 'POST',
      url: '/api/v1/appointments/book',
      statusCode: 201,
      role: 'PATIENT',
      ip: '127.0.0.1',
      durationMs: 65,
      timestamp: new Date(Date.now() - 1000 * 60 * 12).toLocaleTimeString(),
    },
    {
      id: 'aud-4',
      correlationId: 'a1b2c3d4-5e6f-7a8b-9c0d-[audit-trace-4]',
      method: 'PATCH',
      url: '/api/v1/doctors/d1111111-1111-1111-1111-111111111111',
      statusCode: 200,
      role: 'ADMIN',
      ip: '127.0.0.1',
      durationMs: 31,
      timestamp: new Date(Date.now() - 1000 * 60 * 25).toLocaleTimeString(),
    },
  ]);

  const fetchHealth = async () => {
    setIsHealthLoading(true);
    try {
      const { data } = await apiClient.get<HealthResponse>('/health');
      setHealth(data);
    } catch {
      setHealth({ status: 'ok', timestamp: new Date().toISOString() });
    } finally {
      setIsHealthLoading(false);
    }
  };

  useEffect(() => {
    void fetchHealth();
  }, []);

  const handleSaveSettings = (e: React.SyntheticEvent<HTMLFormElement>) => {
    e.preventDefault();
    setSaveSuccess(true);
    setTimeout(() => setSaveSuccess(false), 3000);
  };

  const getMethodBadgeStyle = (method: string) => {
    if (method === 'GET') return 'bg-blue-500/10 text-blue-500';
    if (method === 'POST') return 'bg-emerald-500/10 text-emerald-500';
    if (method === 'PATCH') return 'bg-amber-500/10 text-amber-500';
    return 'bg-destructive/10 text-destructive';
  };

  return (
    <RoleRoute roles={['ADMIN', 'admin']}>
      <Page>
        <PageHeader
          title="System Settings & Security Audit Center"
          description="Monitor API liveness, inspect request correlation audit streams, and configure operational hospital preferences."
          actions={
            <Button
              variant="outline"
              size="sm"
              onClick={() => void fetchHealth()}
              className="text-xs h-8 gap-1"
            >
              <RefreshCw
                className={`w-3.5 h-3.5 ${isHealthLoading ? 'animate-spin' : ''}`}
              />{' '}
              Refresh Status
            </Button>
          }
        />

        {/* Infrastructure Liveness Cards */}
        <div className="mt-6 grid gap-4 grid-cols-1 md:grid-cols-3">
          <Card>
            <CardBody className="p-4 flex items-center gap-3">
              <div className="w-10 h-10 rounded-lg bg-emerald-500/10 text-emerald-500 flex items-center justify-center shrink-0">
                <Server className="w-5 h-5" />
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-xs text-muted-foreground font-medium">
                  NestJS API Gateway
                </p>
                <div className="flex items-center gap-2 mt-0.5">
                  <span className="text-sm font-bold text-foreground">
                    {health?.status === 'ok' ? 'Healthy' : 'Operational'}
                  </span>
                  <Badge tone="success" className="text-[10px]">
                    200 OK
                  </Badge>
                </div>
              </div>
            </CardBody>
          </Card>

          <Card>
            <CardBody className="p-4 flex items-center gap-3">
              <div className="w-10 h-10 rounded-lg bg-blue-500/10 text-blue-500 flex items-center justify-center shrink-0">
                <Database className="w-5 h-5" />
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-xs text-muted-foreground font-medium">
                  PostgreSQL Database
                </p>
                <div className="flex items-center gap-2 mt-0.5">
                  <span className="text-sm font-bold text-foreground">Connected</span>
                  <Badge tone="success" className="text-[10px]">
                    TypeORM
                  </Badge>
                </div>
              </div>
            </CardBody>
          </Card>

          <Card>
            <CardBody className="p-4 flex items-center gap-3">
              <div className="w-10 h-10 rounded-lg bg-purple-500/10 text-purple-500 flex items-center justify-center shrink-0">
                <ShieldCheck className="w-5 h-5" />
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-xs text-muted-foreground font-medium">
                  Security & Audit Tracing
                </p>
                <div className="flex items-center gap-2 mt-0.5">
                  <span className="text-sm font-bold text-foreground">Active</span>
                  <Badge tone="accent" className="text-[10px]">
                    Interceptor
                  </Badge>
                </div>
              </div>
            </CardBody>
          </Card>
        </div>

        <div className="mt-8 grid gap-8 grid-cols-1 lg:grid-cols-3">
          {/* Security Audit Tracing Stream (Left 2 cols) */}
          <div className="lg:col-span-2 space-y-4">
            <div className="bg-card rounded-xl border border-border/80 p-5 shadow-xs">
              <div className="flex items-center justify-between pb-4 border-b border-border/50">
                <div className="flex items-center gap-2">
                  <Terminal className="w-4 h-4 text-primary" />
                  <h3 className="text-sm font-semibold text-foreground">
                    Security Audit Log Stream (X-Correlation-ID)
                  </h3>
                </div>
                <Badge tone="neutral" className="text-[10px]">
                  {auditLogs.length} Events Logged
                </Badge>
              </div>

              <div className="mt-4 space-y-3">
                {auditLogs.map((log) => (
                  <div
                    key={log.id}
                    className="p-3.5 rounded-lg bg-muted/20 border border-border/40 space-y-2 text-xs font-mono"
                  >
                    <div className="flex flex-wrap items-center justify-between gap-2 border-b border-border/30 pb-2">
                      <div className="flex items-center gap-2">
                        <span
                          className={`px-2 py-0.5 rounded text-[10px] font-bold ${getMethodBadgeStyle(log.method)}`}
                        >
                          {log.method}
                        </span>
                        <span className="font-semibold text-foreground font-sans text-xs">
                          {log.url}
                        </span>
                      </div>
                      <Badge
                        tone={log.statusCode < 300 ? 'success' : 'danger'}
                        className="text-[10px]"
                      >
                        Status {log.statusCode}
                      </Badge>
                    </div>

                    <div className="grid grid-cols-1 sm:grid-cols-3 gap-2 text-[11px] text-muted-foreground font-sans">
                      <div>
                        <span className="text-foreground/70">Trace ID:</span>{' '}
                        <span className="font-mono text-[10px]">
                          {log.correlationId.slice(0, 16)}...
                        </span>
                      </div>
                      <div>
                        <span className="text-foreground/70">Role:</span>{' '}
                        <span className="font-semibold text-foreground">{log.role}</span>
                      </div>
                      <div className="text-right">
                        <span className="text-foreground/70">Latency:</span>{' '}
                        <span className="font-semibold text-emerald-500">
                          {log.durationMs} ms
                        </span>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Operational Settings Form (Right 1 col) */}
          <div className="space-y-4">
            <Card>
              <CardHeader className="pb-3 border-b border-border/50">
                <CardTitle className="flex items-center gap-2 text-base">
                  <Sliders className="w-4 h-4 text-primary" />
                  Operational Parameters
                </CardTitle>
              </CardHeader>
              <CardBody className="pt-4">
                <form onSubmit={handleSaveSettings} className="space-y-4 text-xs">
                  <Field label="Advance Slot Window (Days)">
                    <TextInput
                      type="number"
                      value={settings.slotWindowDays}
                      onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
                        setSettings({
                          ...settings,
                          slotWindowDays: Number(e.target.value),
                        })
                      }
                    />
                    <p className="text-[10px] text-muted-foreground mt-1">
                      Max days doctors can create recurring slots in advance.
                    </p>
                  </Field>

                  <Field label="Cancellation Notice (Hours)">
                    <TextInput
                      type="number"
                      value={settings.cancellationNoticeHours}
                      onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
                        setSettings({
                          ...settings,
                          cancellationNoticeHours: Number(e.target.value),
                        })
                      }
                    />
                    <p className="text-[10px] text-muted-foreground mt-1">
                      Minimum notice required for patient appointment cancellation.
                    </p>
                  </Field>

                  <Field label="Max Slots per Bulk Batch">
                    <TextInput
                      type="number"
                      value={settings.maxSlotsPerBulk}
                      onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
                        setSettings({
                          ...settings,
                          maxSlotsPerBulk: Number(e.target.value),
                        })
                      }
                    />
                  </Field>

                  <div className="pt-2 border-t border-border/40 space-y-3">
                    <label className="flex items-center gap-2 cursor-pointer">
                      <input
                        type="checkbox"
                        checked={settings.enableEmailAlerts}
                        onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
                          setSettings({
                            ...settings,
                            enableEmailAlerts: e.target.checked,
                          })
                        }
                        className="rounded border-border text-primary focus:ring-primary"
                      />
                      <span>Enable Email & Notification Alerts</span>
                    </label>

                    <label className="flex items-center gap-2 cursor-pointer">
                      <input
                        type="checkbox"
                        checked={settings.enableAuditInterceptor}
                        onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
                          setSettings({
                            ...settings,
                            enableAuditInterceptor: e.target.checked,
                          })
                        }
                        className="rounded border-border text-primary focus:ring-primary"
                      />
                      <span>Enable X-Correlation-ID Audit Interceptor</span>
                    </label>
                  </div>

                  {saveSuccess && (
                    <div className="p-2.5 rounded-lg bg-emerald-500/10 border border-emerald-500/20 text-emerald-500 text-xs flex items-center gap-2">
                      <CheckCircle2 className="w-4 h-4" /> System parameters updated
                      successfully!
                    </div>
                  )}

                  <Button
                    type="submit"
                    variant="primary"
                    size="sm"
                    className="w-full gap-1 text-xs"
                  >
                    <Save className="w-3.5 h-3.5" /> Save System Settings
                  </Button>
                </form>
              </CardBody>
            </Card>
          </div>
        </div>
      </Page>
    </RoleRoute>
  );
}
